### ISSUE TITLE
How to reproduce the checkpoint

### ISSUE THREAD

**Issue by BUAADreamer** [ABaldrati/CLIP4Cir#10]
Now I run cirr test and get 97.904 in R@50, and R@1/5/10 are also higher than the article's report
Do you know why? Did you update your pretrained models in google drive or the benchmark had some difference?

**Comment by BUAADreamer** [comment]
Oh I see this is because the version of model 
However, I want to ask what GPU did you use and what batch size to train clip-both-finetune
I use 40G A100 and got CUDA out of memory

**Comment by ABaldrati** [comment]
Hi!

As explained in #5 some of the released pre-trained models can have better performance than the published ones.

We fine-tuned both CLIP encoders with a batch size of 128 on a single TITAN RTX (24G) thanks to [gradient checkpointing](https://pytorch.org/docs/stable/checkpoint.html). As stated in the README "The purpose of the code in this repo is to be as clear as possible. For this reason, it does not include some optimizations such as gradient checkpointing (when fine-tuning CLIP) and feature pre-computation (when training the Combiner network)"

However, I think that it should not be difficult to implement it in the code.

If you have other questions do not hesitate to ask!!

**Comment by BUAADreamer** [comment]
Hello! I have another question about learning rate, do you also use same learning rate of 1e-6 as same as in the article?
And besides batch size and learning rate, does any other params that should be ensured to reproduce your checkpoints? Thank you very much!!!

**Comment by BUAADreamer** [comment]
Thank you, I will try my best to reproduce!

**Comment by BUAADreamer** [comment]
Finally, I succeed. When I debug, one thing is important is that **checkpoint should include almost all code in the forward function except for the text encode**. Thanks for the apply!!!
