### ISSUE TITLE
Pre-trained model for evaluation

### ISSUE THREAD

**Issue by haithanhp** [ABaldrati/CLIP4Cir#3]
Thanks for your great work!!!

Do we have pre-trained model to run the testing?

**Comment by ABaldrati** [comment]
Hi!!

Thanks for your interest in our work!!
Pre-trained models are available in the following [Google Drive folder](https://drive.google.com/drive/folders/1ny2hhzP8HZBnXhjvDEni8P8G4_inCNTv?usp=sharing)

If you need more info do not hesitate to ask!
