### ISSUE TITLE
training on multiple gpus on one server

### ISSUE THREAD

**Issue by Chiangsonw** [ABaldrati/CLIP4Cir#6]
hi, i have been grateful for this code. But when running this code, some weird bug came out.
Just running it on a single gpu is ok, but whenever i run this code in multiple gpus, here i mean running the same version of code in different parameters, it always wouldn't work. Training for like a couple of minutes, my server just shutdown. I have been dealing with this problem for some time. I wonder if you ever encountered this problem. If you have met the same situation, i will be grateful if you give the solution towards it.
Thank you a lot.
From a postgraduate who is interested in your work.

**Comment by ABaldrati** [comment]
Hi!
Thanks for your interest in our work!!

I have never encountered such an issue so I am not sure I can help you.
The only thing I can think of is that maybe you run out of CPU RAM memory and the SO kills your process.
Try to set the 'num workers' parameters to a lower number in all the torch dataloader and see what happens.

I hope that can solve your issue!!
If you need more info do not hesitate to ask!

**Comment by Chiangsonw** [comment]
Thanks a lot!!
Your advice has been very helpful! I kept  num_workers to 8 and reduced batchsize to 128 which has been set to 512 in my previous experiments. Now it's working smoothly. 
Anyway, thanks for your solution, i helps a lot!
