### ISSUE TITLE
Retrieve with caption only 

### ISSUE THREAD

**Issue by pntt3011** [ABaldrati/CLIP4Cir#7]
Hi, thank you for this wonderful paper.

I'm intent to use your model to make a fashion recommendation system for my school project.

However, I also want to retrieve a garment based on the caption only. I've tried combining it with a blank image but the result seems not very good.   

Any advices will be highly appreciated.

**Comment by ABaldrati** [comment]
HI!

For what you are trying to achieve I strongly recommend using the out-of-the-box CLIP model (available [here](https://github.com/openai/CLIP)).

I hope it can solve your issue!

**Comment by pntt3011** [comment]
Hi @ABaldrati, thank you for your advice!

I've tested and the result is satisfied enough. I'll close this now.
